# Generated by Django 3.2.9 on 2022-02-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
